### ISSUE TITLE
Dynamic Content

### ISSUE THREAD

**Issue by cosme-benito** [nozzle/nzScrollbar#1]
This scrollbar seems to work okay when the content is static, however it doesn't seem to work with dynamic content. I would suggest an option (such as a service or broadcast) to reload the scrollbar.

Here is a simple replication of the problem by using your own example with an ng-bind: http://codepen.io/anon/pen/RNabJE

**Comment by kotmatpockuh** [comment]
hm... seems that this plugin works bad with angular elastic...
