### ISSUE TITLE
Cross-browser support

### ISSUE THREAD

**Issue by cosme-benito** [nozzle/nzScrollbar#2]
There seems to be issues in some of the major browsers :(

Chrome: works okay

IE 11: scrollbar doesn't show up but it works using mouse scroll wheel

Firefox 34: scrollbar doesn't show up, mouse wheel is extremely slow

**Comment by kotmatpockuh** [comment]
Do not forget!
```
display: (containerHeight) / innerHeight >= 1 ? 'none' : 'initial'
```
will to work in ie10
